export const types = {
	ADD_RECIPE: "ADD_RECIPE",
	DELETE_RECIPE: "DELETE_RECIPE",
	UPDATE_RECIPE: "UPDATE_RECIPE",
	GET_RECIPE: "GET_RECIPE",
	RECIEVE_RECIPES: "RECIEVE_RECIPES",
	CHECK_AUTH_STATUS: "CHECK_AUTH_STATUS",
	LOG_IN: "LOG_IN",
};
