# Generated by Django 3.0.8 on 2020-07-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200713_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='Title',
        ),
    ]
