# Generated by Django 3.0.8 on 2020-07-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200713_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imageUrl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
